/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fenetres;


import pfe.Logique;
import java.awt.HeadlessException;
import pfe.InfLogique;
import pfe.InfSegmentation;
import pfe.Segmentation;

/**
 *
 * @author Taleb
 */
public class Principal extends javax.swing.JFrame {

    // objet contenant le design de l interface graphique 
    Design design;

    InfLogique logique;
    InfSegmentation segmentation;

    /**
     * Creates new form Principal
     *
     * @param design
     */
    public Principal(Design design) throws HeadlessException {
        // creer une instance de la segmentation
        segmentation = new Segmentation();
        // logique c est une class qui represente la logique a suivre pour le pfe
        logique = new Logique();
        // affectation du design
        this.design = design;
        //lancement du design
        design.doDesign(this);
        // initialisation des composants graphiques
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabelAjouterImage = new javax.swing.JLabel();
        jLabelCorrigerBruit = new javax.swing.JLabel();
        jLabelTransformeEnLigne = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabelDetecterLaPlaque = new javax.swing.JLabel();
        jLabelOcrLecture = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        jLabelResultatFinal = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabelSelectedImage = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jLabelSmouthedImage = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jLabelBlackAndWhiteImage = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jLabelLinearImage = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabelDilated = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jLabelErosion = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jLabelSobelFactor = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        jLabelBoundingBoxes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Détection de matricule");
        setBackground(new java.awt.Color(89, 52, 79));
        setName("Form"); // NOI18N

        jPanel1.setName("jPanel1"); // NOI18N

        jPanel3.setBackground(new java.awt.Color(214, 186, 115));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(89, 52, 79), 2));
        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(1024, 30));

        jLabelAjouterImage.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelAjouterImage.setForeground(new java.awt.Color(217, 221, 224));
        jLabelAjouterImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/picture (1).png"))); // NOI18N
        jLabelAjouterImage.setToolTipText("Ajouter Image");
        jLabelAjouterImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelAjouterImage.setName("jLabelAjouterImage"); // NOI18N
        jLabelAjouterImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelAjouterImageMouseClicked(evt);
            }
        });

        jLabelCorrigerBruit.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelCorrigerBruit.setForeground(new java.awt.Color(217, 221, 224));
        jLabelCorrigerBruit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/smooth-line-chart.png"))); // NOI18N
        jLabelCorrigerBruit.setToolTipText("Correction de bruit");
        jLabelCorrigerBruit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelCorrigerBruit.setEnabled(false);
        jLabelCorrigerBruit.setName("jLabelCorrigerBruit"); // NOI18N
        jLabelCorrigerBruit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCorrigerBruitMouseClicked(evt);
            }
        });

        jLabelTransformeEnLigne.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelTransformeEnLigne.setForeground(new java.awt.Color(217, 221, 224));
        jLabelTransformeEnLigne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icon (1).png"))); // NOI18N
        jLabelTransformeEnLigne.setToolTipText("Transformer en Matrice");
        jLabelTransformeEnLigne.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelTransformeEnLigne.setEnabled(false);
        jLabelTransformeEnLigne.setName("jLabelTransformeEnLigne"); // NOI18N
        jLabelTransformeEnLigne.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTransformeEnLigneMouseClicked(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(217, 221, 224));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setName("jSeparator1"); // NOI18N

        jSeparator2.setBackground(new java.awt.Color(217, 221, 224));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setName("jSeparator2"); // NOI18N

        jSeparator3.setBackground(new java.awt.Color(217, 221, 224));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator3.setName("jSeparator3"); // NOI18N

        jSeparator4.setBackground(new java.awt.Color(217, 221, 224));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setName("jSeparator4"); // NOI18N

        jLabelDetecterLaPlaque.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelDetecterLaPlaque.setForeground(new java.awt.Color(217, 221, 224));
        jLabelDetecterLaPlaque.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cube-molecule.png"))); // NOI18N
        jLabelDetecterLaPlaque.setToolTipText("Segmentation & délimitation");
        jLabelDetecterLaPlaque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelDetecterLaPlaque.setEnabled(false);
        jLabelDetecterLaPlaque.setName("jLabelDetecterLaPlaque"); // NOI18N
        jLabelDetecterLaPlaque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDetecterLaPlaqueMouseClicked(evt);
            }
        });

        jLabelOcrLecture.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabelOcrLecture.setForeground(new java.awt.Color(217, 221, 224));
        jLabelOcrLecture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/license-plate.png"))); // NOI18N
        jLabelOcrLecture.setToolTipText("Détection de la plaque");
        jLabelOcrLecture.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelOcrLecture.setEnabled(false);
        jLabelOcrLecture.setName("jLabelOcrLecture"); // NOI18N
        jLabelOcrLecture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelOcrLectureMouseClicked(evt);
            }
        });

        jSeparator5.setBackground(new java.awt.Color(217, 221, 224));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator5.setName("jSeparator5"); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(217, 221, 224));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit (1).png"))); // NOI18N
        jLabel6.setToolTipText("Quitter");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jSeparator6.setBackground(new java.awt.Color(217, 221, 224));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator6.setName("jSeparator6"); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelAjouterImage)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelCorrigerBruit)
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTransformeEnLigne)
                .addGap(18, 18, 18)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDetecterLaPlaque)
                .addGap(18, 18, 18)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelOcrLecture)
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator3)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCorrigerBruit)
                            .addComponent(jLabelTransformeEnLigne)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelOcrLecture)
                            .addComponent(jLabelDetecterLaPlaque))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAjouterImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(245, 224, 183));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(89, 52, 79), 2));
        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setPreferredSize(new java.awt.Dimension(1024, 20));

        jScrollPane10.setBackground(new java.awt.Color(245, 224, 183));
        jScrollPane10.setName("jScrollPane10"); // NOI18N

        jLabelResultatFinal.setBackground(new java.awt.Color(245, 224, 183));
        jLabelResultatFinal.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        jLabelResultatFinal.setForeground(new java.awt.Color(1, 22, 56));
        jLabelResultatFinal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelResultatFinal.setText("Matricule :");
        jLabelResultatFinal.setAutoscrolls(true);
        jLabelResultatFinal.setName("jLabelResultatFinal"); // NOI18N
        jLabelResultatFinal.setOpaque(true);
        jScrollPane10.setViewportView(jLabelResultatFinal);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jPanel4.setBackground(new java.awt.Color(139, 191, 159));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(89, 52, 79), 2));
        jPanel4.setAutoscrolls(true);
        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setPreferredSize(new java.awt.Dimension(1024, 2210));
        jPanel4.setLayout(new java.awt.GridLayout(4, 2));

        jScrollPane2.setBackground(new java.awt.Color(139, 191, 159));
        jScrollPane2.setAutoscrolls(true);
        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jLabelSelectedImage.setBackground(new java.awt.Color(139, 191, 159));
        jLabelSelectedImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSelectedImage.setAutoscrolls(true);
        jLabelSelectedImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelSelectedImage.setName("jLabelSelectedImage"); // NOI18N
        jLabelSelectedImage.setOpaque(true);
        jScrollPane2.setViewportView(jLabelSelectedImage);

        jPanel4.add(jScrollPane2);

        jScrollPane5.setAutoscrolls(true);
        jScrollPane5.setName("jScrollPane5"); // NOI18N
        jScrollPane5.setOpaque(false);

        jLabelSmouthedImage.setBackground(new java.awt.Color(139, 191, 159));
        jLabelSmouthedImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSmouthedImage.setAutoscrolls(true);
        jLabelSmouthedImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelSmouthedImage.setName("jLabelSmouthedImage"); // NOI18N
        jLabelSmouthedImage.setOpaque(true);
        jScrollPane5.setViewportView(jLabelSmouthedImage);

        jPanel4.add(jScrollPane5);

        jScrollPane4.setAutoscrolls(true);
        jScrollPane4.setName("jScrollPane4"); // NOI18N

        jLabelBlackAndWhiteImage.setBackground(new java.awt.Color(139, 191, 159));
        jLabelBlackAndWhiteImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBlackAndWhiteImage.setAutoscrolls(true);
        jLabelBlackAndWhiteImage.setName("jLabelBlackAndWhiteImage"); // NOI18N
        jLabelBlackAndWhiteImage.setOpaque(true);
        jScrollPane4.setViewportView(jLabelBlackAndWhiteImage);

        jPanel4.add(jScrollPane4);

        jScrollPane8.setAutoscrolls(true);
        jScrollPane8.setName("jScrollPane8"); // NOI18N

        jLabelLinearImage.setBackground(new java.awt.Color(139, 191, 159));
        jLabelLinearImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLinearImage.setAutoscrolls(true);
        jLabelLinearImage.setName("jLabelLinearImage"); // NOI18N
        jLabelLinearImage.setOpaque(true);
        jScrollPane8.setViewportView(jLabelLinearImage);

        jPanel4.add(jScrollPane8);

        jScrollPane3.setAutoscrolls(true);
        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jLabelDilated.setBackground(new java.awt.Color(139, 191, 159));
        jLabelDilated.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelDilated.setAutoscrolls(true);
        jLabelDilated.setName("jLabelDilated"); // NOI18N
        jLabelDilated.setOpaque(true);
        jScrollPane3.setViewportView(jLabelDilated);

        jPanel4.add(jScrollPane3);

        jScrollPane6.setAutoscrolls(true);
        jScrollPane6.setName("jScrollPane6"); // NOI18N

        jLabelErosion.setBackground(new java.awt.Color(139, 191, 159));
        jLabelErosion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelErosion.setAutoscrolls(true);
        jLabelErosion.setName("jLabelErosion"); // NOI18N
        jLabelErosion.setOpaque(true);
        jScrollPane6.setViewportView(jLabelErosion);

        jPanel4.add(jScrollPane6);

        jScrollPane7.setAutoscrolls(true);
        jScrollPane7.setName("jScrollPane7"); // NOI18N

        jLabelSobelFactor.setBackground(new java.awt.Color(139, 191, 159));
        jLabelSobelFactor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelSobelFactor.setAutoscrolls(true);
        jLabelSobelFactor.setName("jLabelSobelFactor"); // NOI18N
        jLabelSobelFactor.setOpaque(true);
        jScrollPane7.setViewportView(jLabelSobelFactor);

        jPanel4.add(jScrollPane7);

        jScrollPane9.setAutoscrolls(true);
        jScrollPane9.setName("jScrollPane9"); // NOI18N

        jLabelBoundingBoxes.setBackground(new java.awt.Color(139, 191, 159));
        jLabelBoundingBoxes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBoundingBoxes.setAutoscrolls(true);
        jLabelBoundingBoxes.setName("jLabelBoundingBoxes"); // NOI18N
        jLabelBoundingBoxes.setOpaque(true);
        jScrollPane9.setViewportView(jLabelBoundingBoxes);

        jPanel4.add(jScrollPane9);

        jScrollPane1.setViewportView(jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1061, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1061, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 1061, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        logique.quitter();
    }//GEN-LAST:event_jLabel6MouseClicked

    boolean retry = false;
    private void jLabelAjouterImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelAjouterImageMouseClicked
        // TODO add your handling code here:
        //logique.reset(jLabelCorrigerBruit.isEnabled());

        // load plate est une methode dans logique qui sert a lire la plaque
            logique.loadPlate(jLabelSelectedImage); // lecture de l image est juste
            jLabelCorrigerBruit.setEnabled(true);// activer le click sur la prochaine 
                                                 //  etape qui consiste a corriger le bruit dans l image

    }//GEN-LAST:event_jLabelAjouterImageMouseClicked


    private void jLabelCorrigerBruitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCorrigerBruitMouseClicked
        logique.smoothAndBlur(jLabelSmouthedImage);
        jLabelTransformeEnLigne.setEnabled(true);
    }//GEN-LAST:event_jLabelCorrigerBruitMouseClicked


    private void jLabelTransformeEnLigneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTransformeEnLigneMouseClicked

        segmentation.toB_A_W(jLabelBlackAndWhiteImage); // pour le ocr lecture
        logique.toB_W(jLabelBlackAndWhiteImage);// pour la delimitation
        logique.findLines(jLabelLinearImage);

        jLabelDetecterLaPlaque.setEnabled(true);

    }//GEN-LAST:event_jLabelTransformeEnLigneMouseClicked


    private void jLabelDetecterLaPlaqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDetecterLaPlaqueMouseClicked
        try {

                segmentation.dilate_erose(jLabelErosion, jLabelDilated);
            segmentation.applySobelFactor(jLabelSobelFactor);
            //segmentation.setboundingBoxes(jLabelBoundingBoxes);
            logique.findContours(jLabelBoundingBoxes);
            jLabelOcrLecture.setEnabled(true);
            
            //segmentation.detecteCharactersContour(null);
        } catch (Exception e) {
            System.out.println("error: " + e.getMessage());
        }
    }//GEN-LAST:event_jLabelDetecterLaPlaqueMouseClicked

    private void jLabelOcrLectureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelOcrLectureMouseClicked
        // TODO add your handling code here:
        OCRLogique ocrLogique = new OCRLogique();
        ocrLogique.doOCR(jLabelResultatFinal);
    }//GEN-LAST:event_jLabelOcrLectureMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelAjouterImage;
    private javax.swing.JLabel jLabelBlackAndWhiteImage;
    private javax.swing.JLabel jLabelBoundingBoxes;
    private javax.swing.JLabel jLabelCorrigerBruit;
    private javax.swing.JLabel jLabelDetecterLaPlaque;
    private javax.swing.JLabel jLabelDilated;
    private javax.swing.JLabel jLabelErosion;
    private javax.swing.JLabel jLabelLinearImage;
    private javax.swing.JLabel jLabelOcrLecture;
    private javax.swing.JLabel jLabelResultatFinal;
    private javax.swing.JLabel jLabelSelectedImage;
    private javax.swing.JLabel jLabelSmouthedImage;
    private javax.swing.JLabel jLabelSobelFactor;
    private javax.swing.JLabel jLabelTransformeEnLigne;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
