/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fenetres;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Taleb
 */
public class VisionneuseTraitement extends javax.swing.JFrame {

    /**
     * Creates new form VisionneuseTraitement
     */
    public VisionneuseTraitement() {
        initComponents();
        
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabelImageDebut = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLabelImageResultat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 45, 66), 5));

        jLabel1.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(43, 45, 66));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("  Système de detection et de reconnaissance des plaque d'immatriculation. Imène & Souad");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1374, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(43, 45, 66), 5));

        jLabelImageDebut.setBackground(new java.awt.Color(204, 204, 255));
        jLabelImageDebut.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jLabelImageDebut.setForeground(new java.awt.Color(43, 45, 66));
        jLabelImageDebut.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImageDebut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/template/binary-code-numbers-on-monitor-screen.png"))); // NOI18N
        jLabelImageDebut.setText("Image Chargé");
        jLabelImageDebut.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelImageDebut.setAutoscrolls(true);
        jLabelImageDebut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelImageDebut.setIconTextGap(10);
        jLabelImageDebut.setOpaque(true);
        jLabelImageDebut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jScrollPane1.setViewportView(jLabelImageDebut);

        jScrollPane2.setBackground(new java.awt.Color(204, 204, 255));

        jLabelImageResultat.setBackground(new java.awt.Color(204, 204, 255));
        jLabelImageResultat.setFont(new java.awt.Font("BankGothic Md BT", 1, 24)); // NOI18N
        jLabelImageResultat.setForeground(new java.awt.Color(43, 45, 66));
        jLabelImageResultat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImageResultat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/template/binary-code-numbers-on-monitor-screen.png"))); // NOI18N
        jLabelImageResultat.setText("Image Résultante");
        jLabelImageResultat.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelImageResultat.setAutoscrolls(true);
        jLabelImageResultat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelImageResultat.setIconTextGap(10);
        jLabelImageResultat.setOpaque(true);
        jLabelImageResultat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jScrollPane2.setViewportView(jLabelImageResultat);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(0, 0, 0)
                .addComponent(jScrollPane2))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getImageTraiter(){
        return jLabelImageResultat;
    }
    public void setImageDebut(String image){
        this.jLabelImageDebut.setIcon(new ImageIcon(image));
    }
    public void setImageResultat(String image){
        this.jLabelImageResultat.setIcon(new ImageIcon(image));
    }
    
    
    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelImageDebut;
    private javax.swing.JLabel jLabelImageResultat;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
